# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/86134/Desktop/lab/PinelineCPU/PinelineCPU.srcs/sources_1/ip/I_memory/I_memory.xci
# IP: The module: 'I_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86134/Desktop/lab/PinelineCPU/PinelineCPU.gen/sources_1/ip/I_memory/I_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'I_memory'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/86134/Desktop/lab/PinelineCPU/PinelineCPU.srcs/sources_1/ip/I_memory/I_memory.xci
# IP: The module: 'I_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86134/Desktop/lab/PinelineCPU/PinelineCPU.gen/sources_1/ip/I_memory/I_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'I_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
